# Generated by Django 3.2.6 on 2021-08-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('statusH', models.CharField(choices=[('Extinct', 'EX'), ('Extinct in the Wild', 'EW'), ('Critically Endangered', 'CR'), ('Endangered', 'EN'), ('Vulnerable', 'VU'), ('Near Threatened', 'NT'), ('Conservation Dependent', 'CD'), ('Least Concern', 'LC'), ('Data Deficient', 'DD'), ('Not Listed', 'NE')], default='LC', max_length=255)),
                ('scientaficName', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('source_link', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('tree', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.class')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.class')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.domain')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.family')),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.class')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.domain')),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.kingdom')),
            ],
        ),
        migrations.CreateModel(
            name='Phylum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.domain')),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.kingdom')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.class')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.domain')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.family')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.genus')),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.kingdom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.order')),
                ('phylum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.phylum')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='phylum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.phylum'),
        ),
        migrations.AddField(
            model_name='genus',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.kingdom'),
        ),
        migrations.AddField(
            model_name='genus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.order'),
        ),
        migrations.AddField(
            model_name='genus',
            name='phylum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.phylum'),
        ),
        migrations.AddField(
            model_name='family',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.kingdom'),
        ),
        migrations.AddField(
            model_name='family',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.order'),
        ),
        migrations.AddField(
            model_name='family',
            name='phylum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.phylum'),
        ),
        migrations.AddField(
            model_name='class',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.domain'),
        ),
        migrations.AddField(
            model_name='class',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.kingdom'),
        ),
        migrations.AddField(
            model_name='class',
            name='phylum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.phylum'),
        ),
        migrations.CreateModel(
            name='AnimalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.class'),
        ),
        migrations.AddField(
            model_name='animal',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.domain'),
        ),
        migrations.AddField(
            model_name='animal',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.family'),
        ),
        migrations.AddField(
            model_name='animal',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.genus'),
        ),
        migrations.AddField(
            model_name='animal',
            name='kingdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.kingdom'),
        ),
        migrations.AddField(
            model_name='animal',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.order'),
        ),
        migrations.AddField(
            model_name='animal',
            name='phylum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.phylum'),
        ),
        migrations.AddField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.species'),
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
