# Generated by Django 3.2.6 on 2021-08-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Extinct', 'EX'), ('Extinct in the Wild', 'EW'), ('Critically Endangered', 'CR'), ('Endangered', 'EN'), ('Vulnerable', 'VU'), ('Near Threatened', 'NT'), ('Conservation Dependent', 'CD'), ('Least Concern', 'LC'), ('Data Deficient', 'DD'), ('Not Listed', 'NE')], default='LC', max_length=255),
        ),
        migrations.AlterField(
            model_name='animal',
            name='statusH',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
