# Generated by Django 3.2.6 on 2021-08-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='user',
        ),
    ]
